### ISSUE TITLE
Two typo in README.md

### ISSUE THREAD

**Issue by mrbulb** [liyunsheng13/Efficient-Multi-Domain-Network-Learning-by-Covariance-Normalization#1]
in the `README.md` file's "**Evaluate CovNorm**"'s part , the command line is `python covnorm_eval_adapter_wc.pyt  xxxx`, but there is no `*.pyt` file in the repo.
I think the correct command line should be  `python covnorm_eval_adapter_wc.py  xxxx`

in "**Train Residual Adapter**"'s part , the command line is python `covnorm_train_adpter.py  xxxx`, but there is no `covnorm_train_adpter.py` file in the repo. seems to write `covnorm_train_adapter.py` to `covnorm_train_adpter.py`
I think the correct command line should be  `python covnorm_train_adapter.py  xxxx`

**Comment by liyunsheng13** [comment]
Thank you so much
