### ISSUE TITLE
Dataset's code missing for feature extraction 

### ISSUE THREAD

**Issue by mrbulb** [liyunsheng13/Efficient-Multi-Domain-Network-Learning-by-Covariance-Normalization#2]
Hello, thank you for make your code open source :smile:
https://github.com/liyunsheng13/Efficient-Multi-Domain-Network-Learning-by-Covariance-Normalization/blob/053c589828fbb999243ea6efae111d305143daf7/covnorm_feature_extractor.py#L22
The code above reference `dataset.dataset_feat_extr`, I can not find it in the `dataset` folder, may be the code is missing when uploading? Would you mind upload it to this repo

**Comment by liyunsheng13** [comment]
I'm sorry to cause the inconvenience. You can use the dataset.py to extract features. The dataset_feat_extr.py is almost the same as dataset.py.

**Comment by mrbulb** [comment]
wow, thank you, I'll try it 😄 
My another problem is about **covariance normalization (CovNorm) transform**
In your paper, you formulize this as following formula

![QQ截图20190821101152](https://user-images.githubusercontent.com/30287341/63397121-21567580-c3fc-11e9-83ba-8e1db8f78dd7.jpg)

in the code `vgg_adapter_pca.py` , I think the corresponding part to calculate ![img](http://bit.ly/2Z3AQI9) is as following
https://github.com/liyunsheng13/Efficient-Multi-Domain-Network-Learning-by-Covariance-Normalization/blob/1c2ea182395a720f5c7ba3f6997aaaf019899159/model/vgg_adapter_pca.py#L150

but it seems to be ![img](http://bit.ly/2ZdnoSl) rather than ![img](http://bit.ly/2Z3AQI9)

**Comment by liyunsheng13** [comment]
No, it should be +\mu_y. for the whitening part, we first minus means and times the whitening matrix but for the recoloring part, we need to add the means.

**Comment by mrbulb** [comment]
Yes, I know, but the recoloring part's code seems to minus the means, rather the adding the means

**Comment by liyunsheng13** [comment]
No, the recoloring part should be the inverse PCA. For PCA we first minus mean and times covariance. So for inverse PCA, we should first times the inverse of the covariance matrix and add mean.

**Comment by mrbulb** [comment]
I've got it. Thank you very much for explanation 😄
